### ISSUE TITLE
Primitive Types

### ISSUE THREAD

**Issue by ethanelliott** [ontechsofe/prtflio#53]
- primitive types components, moved to their own folder, for use in #51 
- What types do we need?

**Comment by anirudhmungre** [comment]
- text line
- text area normal
- text area markdown
- image
- video
- icon
- User icon (for adding team members and such)
- title

**Comment by ethanelliott** [comment]
I think the user icon is it's own component and won't need to be a primitive in that sense.

**Comment by anirudhmungre** [comment]
- Skill could be a primitive, like a star rating
